title: Vital Biodiversity
theme: jekyll-theme-minimal

# Navigation (sidebar)
navigation:
  - title: Design Brief
    url: /index.html
  - title: Companion Paper
    url: /companion-paper.html
  - title: Repository
    url: /repository.html
  - title: About
    url: /about.html

defaults:
  - scope:
      path: ""
      type: page
    values:
      sidebar:
        nav: "main"


# Optional: remove theme credit in footer
minimal:
  footer: ""
