title: VITAL BIODIVERSITY SYSTEMS


defaults:
  - scope:
      path: ""
      type: page
    values:
      sidebar:
        nav: "main"


# Optional: remove theme credit in footer
minimal:
  footer: ""
